version: "3.8"
services:
    core-emulator:
        image: secsi/dockerized-android-core-emulator-8.1
        ports:
            - "4242:4242"
            - "6080:6080"
            - "5900:5900"
        networks:
            dockerized-android-emulator-net:
                ipv4_address: 10.0.1.2
        environment:
            TERMINAL: "TRUE"
            APK: "TRUE"
            FORWARD: "TRUE"
            REBOOT: "TRUE"
            DEVICEINFO: "TRUE"
    ui:
        image: secsi/dockerized-android-ui
        ports:
            - "8080:80"
networks:
    dockerized-android-emulator-net:
        ipam:
            config:
                - subnet: 10.0.1.1/24